real_name: Wan2.1-T2V-14B
generator_fsdp_wrap_strategy: size
text_encoder_fsdp_wrap_strategy: size
num_train_timestep: 1000
timestep_shift: 5.0
guidance_scale: 5.0
denoising_loss_type: flow
mixed_precision: true
seed: 0
sharding_strategy: hybrid_full
lr: 1.0e-05
beta1: 0.0
beta2: 0.999
beta1_critic: 0.0
beta2_critic: 0.999
weight_decay: 0.0
data_path: prompts/vidprom_filtered_extended.txt
batch_size: 1
log_iters: 2000
logdir: results_ckpts_100w
negative_prompt: '色调艳丽，过曝，静态，细节模糊不清，字幕，风格，作品，画作，画面，静止，整体发灰，最差质量，低质量，JPEG压缩残留，丑陋的，残缺的，多余的手指，画得不好的手部，画得不好的脸部，畸形的，毁容的，形态畸形的肢体，手指融合，静止不动的画面，杂乱的背景，三条腿，背景人很多，倒着走'
image_or_video_shape:
- 1
- 21
- 16
- 60
- 104
trainer: diffusion
gradient_checkpointing: true
num_frame_per_block: 3
load_raw_video: false
model_kwargs:
  timestep_shift: 5.0

base_paths: [
  merged_videos_latents,
]

metadata_paths: [
  filtered.csv,
]
